# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: marketplace.proto for package 'market'

require 'grpc'
require 'marketplace_pb'

module Market
  module Marketplace
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'market.Marketplace'

      rpc :GetProducts, SearchOptions, Product
    end

    Stub = Service.rpc_stub_class
  end
end
