# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marketplace.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "market.SearchOptions" do
    optional :page, :int32, 1
    optional :per, :int32, 2
    optional :category_eq, :string, 3
  end
  add_message "market.Product" do
    optional :id, :int64, 1
    optional :user_id, :int64, 2
    optional :ext_id, :int64, 3
    optional :category, :string, 4
    optional :name, :string, 5
    optional :promo_text, :string, 6
    optional :description, :string, 7
    optional :country, :string, 8
    optional :lang, :string, 9
    optional :icon, :string, 10
    optional :price, :int64, 11
    optional :created_at, :string, 12
  end
end

module Market
  SearchOptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("market.SearchOptions").msgclass
  Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("market.Product").msgclass
end
