# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marketplace.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "grpc.SearchRequest" do
    optional :page, :int32, 1
    optional :per, :int32, 2
    optional :category_eq, :string, 3
  end
  add_message "grpc.Product" do
    optional :id, :int64, 1
    optional :firm_id, :int64, 2
    optional :category, :enum, 4, "grpc.Category"
    optional :name, :string, 5
    optional :promo_text, :string, 6
    optional :description, :string, 7
    optional :country, :string, 8
    optional :lang, :string, 9
    optional :icon, :string, 10
    optional :price, :int64, 11
    optional :created_at, :string, 12
  end
  add_message "grpc.Identity" do
    optional :id, :int64, 1
  end
  add_enum "grpc.Category" do
    value :CATEGORY_GENERIC, 0
    value :CATEGORY_PERFORMANCE, 1
    value :CATEGORY_ADVANCE, 2
    value :CATEGORY_BASIC, 3
  end
end

module Marketplace
  SearchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.SearchRequest").msgclass
  Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.Product").msgclass
  Identity = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.Identity").msgclass
  Category = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc.Category").enummodule
end
