# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: marketplace.proto for package 'grpc'

require 'grpc'
require_relative './marketplace'

module Marketplace
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'grpc.Marketplace'

    rpc :GetProduct, Identity, Product
    rpc :GetProducts, SearchRequest, stream(Product)
    rpc :CreateProduct, Product, Identity
    rpc :DeleteProduct, Identity, Product
  end

  Stub = Service.rpc_stub_class
end
